### ISSUE TITLE
Error running OnClass-1.2 on custom test datasets when scanorama_batch_correction is true

### ISSUE THREAD

**Issue by rsgoncalves** [wangshenguiuc/OnClass#10]
In running OnClass (release v1.2) on a dataset of our own, the error below occurs when `Run_scanorama_batch_correction=True`. Could you help us figure out why this might be?

```/usr/local/bin/python3.9 /OnClass-1.2/run_OnClass_example.py
read ontology data and initialize training model...
read training single cell data...
embed cell types using the cell ontology...
read test single cell data...
Found 13402 genes among all datasets
[[0.         0.02473551]
 [0.         0.        ]]
(17800, 13402) (6711, 13402)
generate pretrain model. Save the model to $model_path...
Traceback (most recent call last):
  File "/OnClass-1.2/run_OnClass_example.py", line 45, in <module>
    cor_train_feature, cor_test_feature, cor_train_genes, cor_test_genes = OnClass_train_obj.ProcessTrainFeature(train_feature, train_label, train_genes, test_feature=test_feature, test_genes=test_genes)
  File "/OnClass-1.2/OnClass/OnClassModel.py", line 92, in ProcessTrainFeature
    train_feature, test_feature, selected_train_genes = process_expression(train_feature, test_feature, train_genes, test_genes)
  File "/OnClass-1.2/OnClass/OnClass_utils.py", line 334, in process_expression
    test_X = map_genes(test_X, test_genes, train_genes)
  File "/OnClass-1.2/OnClass/OnClass_utils.py", line 115, in map_genes
    new_test_x[:,ind1] = test_X[:,ind2]
  File "/usr/local/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 193, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 16670 is out of bounds for axis 1 with size 13402```

**Comment by wangshenguiuc** [comment]
Hi, thank you for using OnClass.
We used Run_scanorama_batch_correction to do batch correction. I will look into this issue soon.

But for now, one solution is to first run Scanorama or any batch correction method you like before passing the training/test data to OnClass. After you have done batch correction on your side, you can set Run_scanorama_batch_correction = False and then run OnClass on the batch corrected data.

**Comment by canergen** [comment]
Inactive and I'm not able to reproduce it. Please reopen if this issue still exists.
