### ISSUE TITLE
Error with run_OnClass_example.py

### ISSUE THREAD

**Issue by lgeistlinger** [wangshenguiuc/OnClass#11]
Hi, I am trying to get the [Onclass example](https://onclass.readthedocs.io/en/latest/Tutorial.html.) to run, and I am getting to [line 46](https://github.com/wangshenguiuc/OnClass/blob/07b2917dbdf01a1de54771de3383bbaa4bb2f283/run_OnClass_example.py#L46), where things are breaking:

``` 
>>> OnClass_train_obj.Train(cor_train_feature, train_label, save_model = model_path, max_iter = MAX_ITER)
/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)
Training cost after epoch 1: loss:3.011955 acc: 0.551 auc: 0.676 auprc: 0.011
Traceback (most recent call last):
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    target_list, run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1455, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.PermissionDeniedError: /n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/data/Pretrained_model/example_file_model.data-00000-of-00001.tempstate7866399343006310431; Permission denied
	 [[{{node save/SaveV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 135, in Train
    self.model.optimize(max_iter = max_iter, minibatch_size = minibatch_size, save_model =  save_model)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 213, in optimize
    self.saver.save(self.sess, save_model)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1274, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1371, in _do_run
    run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.PermissionDeniedError: Graph execution error:

Detected at node 'save/SaveV2' defined at (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 84, in BuildModel
      self.model = BilinearNN(self.co2emb, self.nseen, self.ngene, use_pretrain = use_pretrain, nhidden=self.nhidden)
    File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 36, in __init__
      self.saver = tf.train.Saver()
Node: 'save/SaveV2'
/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/data/Pretrained_model/example_file_model.data-00000-of-00001.tempstate7866399343006310431; Permission denied
	 [[{{node save/SaveV2}}]]

Original stack trace for 'save/SaveV2':
  File "<stdin>", line 1, in <module>
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 84, in BuildModel
    self.model = BilinearNN(self.co2emb, self.nseen, self.ngene, use_pretrain = use_pretrain, nhidden=self.nhidden)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 36, in __init__
    self.saver = tf.train.Saver()
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 919, in __init__
    self.build()
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 931, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 969, in _build
    build_restore=build_restore)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 527, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 219, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 135, in save_op
    tensors)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1716, in save_v2
    name=name)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3784, in _create_op_internal
    op_def=op_def)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

>>> x = read_h5ad(test_file)
>>> print ('generate pretrain model. Save the model to $model_path...')
generate pretrain model. Save the model to $model_path...
>>> cor_train_feature, cor_test_feature, cor_train_genes, cor_test_genes = OnClass_train_obj.ProcessTrainFeature(train_feature, train_label, train_genes, test_feature = test_feature, test_genes = test_genes)

>>> OnClass_train_obj.BuildModel(ngene = len(cor_train_genes), nhidden = NHIDDEN)
<OnClass.BilinearNN.BilinearNN object at 0x7f1e55014b50>
>>> OnClass_train_obj.Train(cor_train_feature, train_label, save_model = model_path, max_iter = MAX_ITER)
/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)
Training cost after epoch 1: loss:3.011955 acc: 0.551 auc: 0.676 auprc: 0.011
Traceback (most recent call last):
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    target_list, run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1455, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.PermissionDeniedError: /n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/data/Pretrained_model/example_file_model.data-00000-of-00001.tempstate719271341183877227; Permission denied
	 [[{{node save/SaveV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 135, in Train
    self.model.optimize(max_iter = max_iter, minibatch_size = minibatch_size, save_model =  save_model)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 213, in optimize
    self.saver.save(self.sess, save_model)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1274, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1371, in _do_run
    run_metadata)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.PermissionDeniedError: Graph execution error:

Detected at node 'save/SaveV2' defined at (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 84, in BuildModel
      self.model = BilinearNN(self.co2emb, self.nseen, self.ngene, use_pretrain = use_pretrain, nhidden=self.nhidden)
    File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 36, in __init__
      self.saver = tf.train.Saver()
Node: 'save/SaveV2'
/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/data/Pretrained_model/example_file_model.data-00000-of-00001.tempstate719271341183877227; Permission denied
	 [[{{node save/SaveV2}}]]

Original stack trace for 'save/SaveV2':
  File "<stdin>", line 1, in <module>
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/OnClassModel.py", line 84, in BuildModel
    self.model = BilinearNN(self.co2emb, self.nseen, self.ngene, use_pretrain = use_pretrain, nhidden=self.nhidden)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/OnClass/BilinearNN.py", line 36, in __init__
    self.saver = tf.train.Saver()
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 919, in __init__
    self.build()
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 931, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 969, in _build
    build_restore=build_restore)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 527, in _build_internal
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 219, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 135, in save_op
    tensors)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1716, in save_v2
    name=name)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3784, in _create_op_internal
    op_def=op_def)
  File "/n/data1/hms/ccb/lab/projects/hematopoiesis_atlas/code/OnClass-1.2/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

I am using python 3.7.4. Do you have suggestions on how to best fix that. Thanks!

**Comment by lgeistlinger** [comment]
Ah - it's just a permission denied error. Sorry, nvm.
